// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { asset } from '@/lib/base-path'

const MODEL_URL = asset('/threed/fairino.glb')

export function Model(props) {
  const { nodes, materials } = useGLTF(MODEL_URL)
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 4, 0]}>
        <group position={[0, -0.001, 0]} rotation={[Math.PI, -0.949, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid1_1.geometry}
            material={materials.SmoothWhite}
            position={[0, 0.144, 0.003]}
            scale={0.07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid2.geometry}
            material={materials.SmoothWhite}
            position={[0, 0.213, 0]}
            scale={0.058}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid3.geometry}
            material={materials.SmoothWhite}
            position={[0.037, 0.211, 0.037]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid4.geometry}
            material={materials.SmoothWhite}
            position={[0.037, 0.211, -0.037]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid5.geometry}
            material={materials.SmoothWhite}
            position={[-0.037, 0.211, -0.037]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid6.geometry}
            material={materials.SmoothWhite}
            position={[-0.037, 0.211, 0.037]}
            scale={0.005}
          />
        </group>
        <group position={[0.085, 0.198, -0.117]} rotation={[-Math.PI, -0.949, 1.258]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid1_2.geometry}
            material={materials.SmoothWhite}
            position={[-0.037, 0.115, 0.197]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid2_1.geometry}
            material={materials.SmoothWhite}
            position={[-0.388, 0.189, 0.197]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid3_1.geometry}
            material={materials.SmoothWhite}
            position={[0.037, 0.115, 0.197]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid4_1.geometry}
            material={materials.SmoothWhite}
            position={[-0.213, 0.152, 0.132]}
            scale={0.271}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid5_1.geometry}
            material={materials.SmoothWhite}
            position={[-0.037, 0.189, 0.197]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid6_1.geometry}
            material={materials.SmoothWhite}
            position={[-0.462, 0.115, 0.197]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid7.geometry}
            material={materials.SmoothWhite}
            position={[-0.462, 0.189, 0.197]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid8.geometry}
            material={materials.SmoothWhite}
            position={[0.037, 0.189, 0.197]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid9.geometry}
            material={materials.SmoothWhite}
            position={[-0.388, 0.115, 0.197]}
            scale={0.005}
          />
        </group>
        <group position={[-0.038, 1.002, 0.054]} rotation={[Math.PI, -0.949, -1.083]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid1_3.geometry}
            material={materials.SmoothWhite}
            position={[-0.795, 0.127, -0.043]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid2_2.geometry}
            material={materials.SmoothWhite}
            position={[-0.435, 0.152, 0.012]}
            scale={0.068}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid3_2.geometry}
            material={materials.SmoothWhite}
            position={[-0.502, 0.152, 0]}
            scale={0.038}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid4_2.geometry}
            material={materials.SmoothWhite}
            position={[-0.845, 0.127, -0.043]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid5_2.geometry}
            material={materials.SmoothWhite}
            position={[-0.795, 0.177, -0.043]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid6_2.geometry}
            material={materials.SmoothWhite}
            position={[-0.845, 0.177, -0.043]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid7_1.geometry}
            material={materials.SmoothWhite}
            position={[-0.681, 0.152, 0.006]}
            scale={0.179}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid8_1.geometry}
            material={materials.SmoothWhite}
            position={[-0.82, 0.152, -0.046]}
            scale={0.04}
          />
        </group>
        <group position={[-0.669, 0.227, 0.935]} rotation={[Math.PI, -0.949, -2.934]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid1_4.geometry}
            material={materials.Default}
            position={[-0.82, 0.198, 0.102]}
            scale={0.04}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid2_3.geometry}
            material={materials.Default}
            position={[-0.795, 0.195, 0.077]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid3_3.geometry}
            material={materials.Default}
            position={[-0.82, 0.146, 0.098]}
            scale={0.052}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid4_3.geometry}
            material={materials.Default}
            position={[-0.845, 0.195, 0.077]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid5_3.geometry}
            material={materials.Default}
            position={[-0.845, 0.195, 0.127]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid6_3.geometry}
            material={materials.Default}
            position={[-0.795, 0.195, 0.127]}
            scale={0.005}
          />
        </group>
        <group position={[0.536, 0.011, 0.271]} rotation={[-1.74, 0.12, 0.014]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid1_5.geometry}
            material={materials.Default}
            position={[-0.795, 0.025, 0.059]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid2_4.geometry}
            material={materials.Default}
            position={[-0.82, 0.05, 0.056]}
            scale={0.04}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid3_4.geometry}
            material={materials.Default}
            position={[-0.82, 0.054, 0.108]}
            scale={0.052}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid4_4.geometry}
            material={materials.Default}
            position={[-0.845, 0.075, 0.059]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid5_4.geometry}
            material={materials.Default}
            position={[-0.795, 0.075, 0.059]}
            scale={0.005}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid6_4.geometry}
            material={materials.Default}
            position={[-0.845, 0.025, 0.059]}
            scale={0.005}
          />
        </group>
        <group position={[-0.272, 0.156, 0.207]} rotation={[0.003, 0.956, 2.932]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Solid1_6.geometry}
            material={materials.Default}
            position={[0, 0.022, 0]}
            scale={0.04}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Solid1.geometry}
          material={materials.Default}
          position={[0, 0.034, 0]}
          scale={0.333}
        />
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_URL)