name: Build for GitHub Pages

on: push

permissions:
  contents: write

jobs:
  build:
    name: Build for GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Build website
        run: |
          yarn install --frozen-lockfile
          yarn build
